Update Dockerfile

diff --git a/docker/images/n8n/Dockerfile b/docker/images/n8n/Dockerfile
--- a/docker/images/n8n/Dockerfile
+++ b/docker/images/n8n/Dockerfile
@@ -1,8 +1,8 @@
 ARG NODE_VERSION=20
 FROM n8nio/base:${NODE_VERSION}
 
-ARG N8N_VERSION
-RUN if [ -z "$N8N_1.77.0" ] ; then echo "The N8N_VERSION argument is missing!" ; exit 1; fi
+ARG N8N_1.77.0
+RUN if [ -z "$N8N_VERSION" ] ; then echo "The N8N_VERSION argument is missing!" ; exit 1; fi
 
 LABEL org.opencontainers.image.title="n8n"
 LABEL org.opencontainers.image.description="Workflow Automation Tool"
